import = [
    "~/.config/alacritty/rose-pine.toml"
]

[font]
size = 18.0
normal = { family = "FiraMono Nerd Font", style = "Regular" }

[cursor]
# thickness = 1.0

[env]
TERM='alacritty-direct'

[window]
dynamic_padding = true
opacity = 0.97

[shell]
program = "/bin/zsh"
