
[font]
size = 12.0
normal = { family = "FiraMono Nerd Font", style = "Regular" }

[cursor]
# thickness = 1.0

[env]
TERM='alacritty-direct'

[window]
dynamic_padding = true
opacity = 0.99

[general]
import = [
    "~/.config/alacritty/dracula.toml"
    # "~/.config/alacritty/rose-pine.toml"
]

[terminal]

[terminal.shell]
program = "/bin/zsh"
