import = [
    "~/.config/alacritty/rose-pine.toml"
]

[font]
size = 16.0
normal = { family = "RobotoMono Nerd Font", style = "Regular" }

[cursor]
#thickness = 1.0
[env]
TERM='alacritty-direct'

[window]
startup_mode = 'Maximized'
decorations = 'none'
dynamic_padding = true
padding = { x = 3, y = 3 }
opacity = 0.95

#[shell]
#program = "/bin/zsh"
