import = [
    "~/.config/alacritty/themes/themes/onedark.toml"
]

[font]
size = 14.0
normal = { family = "Roboto Mono", style = "Regular" }

[cursor]
#thickness = 1.0
[env]
TERM='alacritty-direct'

[window]
dynamic_padding = true
padding = { x = 3, y = 3 }
opacity = 1.0

[shell]
program = "/bin/zsh"
