[font]
size = 12.0
# normal = { family = "FiraMono Nerd Font", style = "Regular" }
normal = { family = "JetBrainsMono", style = "Regular" }

[cursor]
thickness = 0.5

[env]
TERM='alacritty-direct'

[window]
dynamic_padding = true
opacity = 0.99

[general]
import = [
    #"~/.config/alacritty/dracula.toml"
    "~/.config/alacritty/catppuccin-mocha.toml"
]

[terminal]

[terminal.shell]
program = "/bin/zsh"
