[font]
size = 12.0
# normal = { family = "FiraMono Nerd Font", style = "Regular" }
normal = { family = "JetBrainsMono", style = "Regular" }

[cursor]
thickness = 0.3

[env]
TERM='alacritty-direct'

[window]
dynamic_padding = true
opacity = 1.0
decorations = "None"

[window.padding]
x = 10
y = 10

[general]
import = [
    "~/.config/alacritty/catppuccin-mocha.toml"
]

[terminal]

[terminal.shell]
program = "/bin/zsh"
